In [1]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

In [2]:
df = pd.read_csv("/Users/fesavaskurt/Python&ML/Kodlarım/Python/datasets/Python Datasets/norway_new_car_sales_by_model.csv", encoding='latin')

In [3]:
df.head()

   Year  Month         Make              Model  Quantity   Pct
0  2007      1  Volkswagen   Volkswagen Passat      1267  10.0
1  2007      1      Toyota         Toyota Rav4       819   6.5
2  2007      1      Toyota      Toyota Avensis       787   6.2
3  2007      1  Volkswagen     Volkswagen Golf       720   5.7
4  2007      1      Toyota      Toyota Corolla       691   5.4

In [4]:
df.groupby(["Year", "Make"]).mean(numeric_only= True)

                      Month    Quantity       Pct
Year Make
2007 Audi          6.045455  188.000000  1.727273
     BMW           1.500000  166.000000  1.450000
     Ford          6.590909  271.636364  2.531818
     Honda         6.500000  264.583333  2.475000
     Mitsubishi   10.000000  302.800000  2.980000
...                     ...         ...       ...
2017 Skoda         1.000000  281.500000  2.150000
     Tesla         1.000000  238.000000  1.800000
     Toyota        1.000000  335.500000  2.550000
     Volkswagen    1.000000  626.500000  4.800000
     Volvo         1.000000  270.250000  2.050000

[161 rows x 3 columns]

In [5]:
df.groupby("Year")["Quantity"].agg(sum)

/var/folders/sj/pj9lwv9d1r17b6cggf8ym3gc0000gn/T/ipykernel_9971/3905085766.py:1: FutureWarning: The provided callable <built-in function sum> is currently using SeriesGroupBy.sum. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "sum" instead.
  df.groupby("Year")["Quantity"].agg(sum)

Year
2007    69749
2008    57789
2009    49373
2010    61572
2011    64009
2012    66150
2013    76770
2014    72234
2015    78947
2016    93016
2017     6834
Name: Quantity, dtype: int64

In [6]:
df.groupby(["Year", "Make"])["Quantity"].agg(sum)

/var/folders/sj/pj9lwv9d1r17b6cggf8ym3gc0000gn/T/ipykernel_9971/1506103351.py:1: FutureWarning: The provided callable <built-in function sum> is currently using SeriesGroupBy.sum. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "sum" instead.
  df.groupby(["Year", "Make"])["Quantity"].agg(sum)

Year  Make
2007  Audi           4136
      BMW             332
      Ford           5976
      Honda          3175
      Mitsubishi     1514
                     ...
2017  Skoda           563
      Tesla           238
      Toyota         1342
      Volkswagen     1253
      Volvo          1081
Name: Quantity, Length: 161, dtype: int64

In [9]:
data_toyota = df[df["Make"] == 'Toyota ']

In [11]:
data_toyota.sort_values(by = "Quantity", ascending= False).head()

      Year  Month     Make           Model  Quantity  Pct
1     2007      1  Toyota      Toyota Rav4       819  6.5
2     2007      1  Toyota   Toyota Avensis       787  6.2
2574  2016      8  Toyota      Toyota Rav4       735  5.6
4     2007      1  Toyota   Toyota Corolla       691  5.4
1689  2013     10  Toyota     Toyota Auris       679  5.3

In [12]:
## Remove the space character in make column

In [13]:
"Toyota ".strip()

'Toyota'

In [16]:
df["Make"] = df["Make"].str.upper()

In [17]:
df["Make"] = df["Make"].str.strip()

In [19]:
df["Make"].unique()

array(['VOLKSWAGEN', 'TOYOTA', 'PEUGEOT', 'SKODA', 'FORD', 'VOLVO',
       'AUDI', 'OPEL', 'BMW', 'HONDA', 'SAAB', 'MITSUBISHI', 'NISSAN',
       'MAZDA', 'SUBARU', 'HYUNDAI', 'SUZUKI', 'KIA', 'MERCEDES-BENZ',
       'CITROEN', 'TESLA', 'RENAULT'], dtype=object)

In [20]:
df["Make"].nunique()

22

In [22]:
df["Model"] = df["Model"].str.title()

In [24]:
df["Model"].nunique()

89

### Function Application and Mapping

* Apply tablonun kolonlarına çalışırken map tablonun satırlarına çalışır. Yani map hücre hücre çalışıyor, apply direkt tüm kolonlara.
* Her iki fonksiyon da dataframe veya series içerisinde uygulamalar yapmak için kullanılır.

In [26]:
frame = pd.DataFrame(np.random.randint(0,10,(4,3)), columns= list('bde'),
                     index = ["Utah", "Ohio", "Texas", "Oregon"])

In [27]:
frame

        b  d  e
Utah    2  0  3
Ohio    2  6  2
Texas   4  3  4
Oregon  6  0  8

In [28]:
frame.min()

b    2
d    0
e    2
dtype: int64

In [29]:
frame.max()

b    6
d    6
e    8
dtype: int64

In [30]:
f = lambda x: x.max() - x.min()

In [31]:
frame.apply(f)

b    4
d    6
e    6
dtype: int64

In [32]:
## map

In [33]:
myfunct = lambda x: x**2

In [34]:
frame.map(myfunct)

         b   d   e
Utah     4   0   9
Ohio     4  36   4
Texas   16   9  16
Oregon  36   0  64

In [38]:
def f(x):
    if type(x) == str:
        return x.strip()
    else:
        return x
### Tüm hücrelere git, stringse strip koy değil ise hiçbir şey yapma.

In [37]:
df.map(f)

      Year  Month        Make              Model  Quantity   Pct
0     2007      1  VOLKSWAGEN  Volkswagen Passat      1267  10.0
1     2007      1      TOYOTA        Toyota Rav4       819   6.5
2     2007      1      TOYOTA     Toyota Avensis       787   6.2
3     2007      1  VOLKSWAGEN    Volkswagen Golf       720   5.7
4     2007      1      TOYOTA     Toyota Corolla       691   5.4
...    ...    ...         ...                ...       ...   ...
2689  2017      1     PEUGEOT       Peugeot 3008       216   1.7
2690  2017      1         KIA           Kia Niro       214   1.6
2691  2017      1       SKODA       Skoda Superb       205   1.6
2692  2017      1         BMW        Bmw 2-Serie       202   1.5
2693  2017      1       VOLVO          Volvo V90       202   1.5

[2694 rows x 6 columns]